site_name: Мой сайт
site_url: https://sitename.example
# Навигация
nav:
  - Блог:
    - blog/index.md
  - Руководство:
    - install.md
    - git.md
    - admonitions.md
    - code-exampel.md
    - content-tabs.md
    - diagram-examples.md
    - equations.md
    - setki.md 
  - Путешествия:
     - Россия:
        - Санкт-Петербург.md
        - Псков.md
        - Калуга.md
        - Приозерск.md
# Конфигурация
theme:
  name: material
  language: ru
  logo: assets/logo.png
  favicon: images/favicon.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
# Расширения
markdown_extensions:
  - admonition #Рекомендации https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.details #Рекомендации
  - pymdownx.superfences #Рекомендации
  - attr_list # Списки атрибутов
  - def_list # Списки определений https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
  - footnotes # Сноски https://python-markdown.github.io/extensions/footnotes/
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
  - tables
  - pymdownx.superfences: # Диаграммы
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic 
  - pymdownx.caret # Выделение текста
  - pymdownx.keys # Выделение клавиш
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex: # Математические формулы
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji: # Смайлики
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist: # Списки
      custom_checkbox: true
# Javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
# Пиздец полный
# GIt это словно сортировочная станция
# Пиздец тотальный короче